### ISSUE TITLE
Adjust to 60hz or whichever tick rate is chosen.

### ISSUE THREAD

**Issue by WatIsDeze** [PalmliXStudios/Polyhedron-Engine#9]
We'll need to come up with a method that is as easy and little annoying as possible in order to have the game run as if it were back in the day, while still being 60hz.

For example, animations are currently stored as integers (ouch) and this becomes problematic, especially if game code depends on it. Like shooting 6 blaster bolts or so a second is really not good. (Looks funny though)

- [X] Get viewbob and footsteps to work again.
- [ ] Get the network to play kindly with it again. Slightly related to #5

**Comment by WatIsDeze** [comment]
So far I suddenly got caught up in old bugs related to not being able to do this twice: gamemap name ; gamemap name; because the second time it could not find a spawn point. 

The point being, the entire game mode stuff was a little messed up. Currently looks fixed to almost perfection. Did fix some 60hz things here and there, but the viewbob and footstep is still a big @#!@$@#$% on how to even do that. Maybe just rewrite it as is anyway?

**Comment by PalmliX** [comment]
I vote for re-writing it as it is, because I'd like to make weapons, and its hard to know how a weapon's idle or other animations should look if it's moving around like crazy when you walk. So maybe for now just do the "quick fix" of re-writing it for 60hz, so we can least test new weapons out. Same kind of thing for footstep sounds actually, it will be easier to test new sounds if the playback is "correct" in-game.

I definitely see the point of coming up with a new system that is not hardcoded to 60hz (or whichever), which totally makes sense for actual content (model animations etc.) but for the viewbobs and footsteps, I feel like its not as big a deal to hard code it for 60hz because that is not likely to change, or need changing?

**Comment by WatIsDeze** [comment]
> 
> 
> I vote for re-writing it as it is, because I'd like to make weapons, and its hard to know how a weapon's idle or other animations should look if it's moving around like crazy when you walk. So maybe for now just do the "quick fix" of re-writing it for 60hz, so we can least test new weapons out. Same kind of thing for footstep sounds actually, it will be easier to test new sounds if the playback is "correct" in-game.
> 
> I definitely see the point of coming up with a new system that is not hardcoded to 60hz (or whichever), which totally makes sense for actual content (model animations etc.) but for the viewbobs and footsteps, I feel like its not as big a deal to hard code it for 60hz because that is not likely to change, or need changing?

You're correct, from what I can tell we'll stick to 60hz, if for whatever reason that fails, 40hz will do. Speaking off, I got told animations are best made at 30fps anyhow. @Paril knows more about this.

**Comment by WatIsDeze** [comment]
Currently in the process of moving over some functions that should not all belong in PlayerClient and/or GameMode but in World instead, however it is very likely the bob/footstep issue would then be resolved.

That leaves us then only still with the animations to cover. Deathmatch modes seem to play fine, and so does single player. Save/Load can not be done yet until serialization is made use of.

**Comment by WatIsDeze** [comment]
BobMove + Footsteps are on. Most of this takes place in void GameModeName::ClientEndServerFrame(), and PlayerClient::SetEvent.

I'd like to add in ClientEndServerFrameas a method to the client's class instead, to perhaps spare some extra lines of code in the gamemode classes.

**Comment by WatIsDeze** [comment]
Going to open various new ones with more specific matters.
